###User Signup Endpoint
POST http://localhost:3001/v1/user
Content-Type: application/json


{
    "name":"Mudit",
    "company":"ZPR",
    "address":"magadi",
    "phone":"7044633714",
    "email":"muditnawalgaria108@gmail.com",
    "password":"abcsadasdasdd"
}



###User SignIN Endpoint
POST http://localhost:3001/v1/user/login
Content-Type: application/json

{
    "email":"muditnawalgaria108@gmail.com",
    "password":"abcsadasdasdd"
}